mutation calendarAddCodeReviewToEventSlot($studentGoalId: ID!, $startTime: DateTime!) {
  student {
    addBookingCodeReviewToEventSlot(
      studentGoalId: $studentGoalId
      startTime: $startTime
    ) {
      id
    }
  }
}