mutation CalendarUpdateFilledChecklistWithOnlineReview($filledChecklistId: ID!) {
  school21 {
    submitFilledChecklistRecording(filledChecklistId: $filledChecklistId) {
      checklistId
    }
  }
}