query calendarGetCodeReviewData($studentGoalId: ID!) {
  student {
    getStudentModuleByStudentGoalId(studentGoalId: $studentGoalId) {
      moduleTitle
      currentTask {
        task {
          studentTaskAdditionalAttributes {
            codeReviewDuration
          }
        }
      }
    }
  }
}