query CalendarGetVideoInNotFinalStatus($filledChecklistId: ID!) {
  sc21StudentTaskCheck {
    getVideoInNotFinalStatus(filledChecklistId: $filledChecklistId) {
      onlineVideoId
      link
      status
      statusDetails
      updateDateTime
    }
  }
}