query competitionCoalitionGetMyCoalitionMembers($page: PagingInput) {
  student {
    getMyCoalitionMembers(page: $page) {
      user {
        id
        login
        avatarUrl
        userExperience {
          level {
            id
            levelCode
          }
        }
      }
    }
  }
}