mutation createParticipantEvent($input: ActivityEventByStudentInputModel!) {
  event {
    createParticipantEvent(input: $input) {
      activityEventId
      eventId
      name
      eventType
    }
  }
}