fragment AsapWidget on AsapWidgetInfo {
  shortImg
  shortTitle
  shortUrl
  startDate
  finishDate
  showFinishDate
  fullTitle
  text
  fullImgUrl
  adtTypeId
  adtWidgetId
}

query getAsapWidgets {
  student {
    getAsapWidgetList {
      widgetList {
        ...AsapWidget
      }
    }
  }
}