fragment AsapWidget on ASAPMessage {
  smallImageUrl
  smallTitle
  smallUrl
  startDate
  finishDate
  showFinishDate
  fullTitle
  fullText
  fullImageUrl
  adtType
  adtWidgetId
}

query getAsapWidgets {
  ASAP {
    getASAPMessages {
      ...AsapWidget
    }
  }
}