fragment CoinsTransactionInfo on UserCoinsHistoryItemModel {
  id
  itemType
  amount
  date
  badgeName
  badgeAvatar
  externalTransactionId
  giverLogin
  comment
  amountAfter
  tournamentName
}

query getCoinsHistory {
  student {
    getUserCoinsHistory {
      ...CoinsTransactionInfo
    }
  }
}