query getCourseConsistencyInfo($localCourseId: ID!) {
  school21 {
    loadCourseConsistencyInfo(localCourseId: $localCourseId) {
      courseId
      name
      isConsistent
      isConstructorsValid
    }
  }
}