query getCourseAttemptStatistic($localCourseId: ID!) {
  course {
    getCourseAttemptStatistic(localCourseId: $localCourseId) {
      resultDate
      finalPercentage
      pointProject
      completionResultStatus
    }
  }
}