fragment CodeReviewCurrentTaskInfo on StudentTask {
  id
  taskId
  task {
    content {
      body
    }
    assignmentType
    studentTaskAdditionalAttributes {
      codeReviewDuration
      codeReviewCost
    }
    translatedData
  }
}

fragment CodeReviewProjectInfo on StudentModule {
  id
  moduleTitle
  studyModule {
    duration
    stage {
      name
    }
  }
  currentTask {
    ...CodeReviewCurrentTaskInfo
  }
}

query getCodeReviewProjectInfo($studentGoalId: ID!, $language: String) {
  student {
    getStudentModuleByStudentGoalId(
      studentGoalId: $studentGoalId
      language: $language
    ) {
      ...CodeReviewProjectInfo
    }
  }
}