query getCampusBuildings {
  student {
    getBuildings {
      id
      name
      classrooms {
        id
        number
        capacity
        availableCapacity
        floor
        classroomPlan {
          classroomPlanId
          planMeta
        }
        specializations
      }
    }
  }
}