fragment FormChecklistQuestion on SectionQuestion {
  sectionQuestionId
  name
  description
  taskAssessmentScale {
    criterionScaleId
    type
    description
    scaleWeights {
      key
      value
    }
  }
}

fragment FormChecklistSection on ChecklistSection {
  checklistSectionId
  name
  description
  kindQuestionId
  questionList {
    ...FormChecklistQuestion
  }
}

fragment OnlineReviewInfo on OnlineReview {
  isOnline
  videos {
    onlineVideoId
    link
    status
    statusDetails
    updateDateTime
    fileSize
  }
}

fragment TeamMemberUser on User {
  id
  avatarUrl
  login
  userExperience {
    level {
      id
      levelCode
      range {
        levelCode
      }
    }
    cookiesCount
    codeReviewPoints
  }
  activeSchoolShortName
}

fragment TeamMember on TeamMember {
  user {
    ...TeamMemberUser
  }
  role
}

fragment FilledChecklistModuleInfo on ModuleInfoP2P {
  moduleName
  executionType
  periodOfVerification
}

fragment FormChecklist on Checklist {
  introduction
  guidelines
  sectionList {
    ...FormChecklistSection
  }
  quickActions
  availableLanguages
  languageCode
}

fragment ChecklistSolutionInfo on SolutionInfo {
  solutionType
  gitlabSolutionInfo {
    gitlabLink {
      id
      sshLink
      httpsLink
    }
  }
  platfSolutionInfo {
    comment
    files {
      studyProcessFileId
      link
      creatorLogin
      fileExtension
      fileSize
    }
  }
}

query getFilledChecklist($filledChecklistId: ID!, $languageCodeType: LanguageCodeType) {
  student {
    getP2pInfo(
      filledChecklistId: $filledChecklistId
      languageCodeType: $languageCodeType
    ) {
      id
      solutionInfo {
        ...ChecklistSolutionInfo
      }
      checklist {
        ...FormChecklist
      }
      moduleInfoP2P {
        ...FilledChecklistModuleInfo
      }
      progressCheckInfo {
        reviewUserCount
        reviewUserCountExecuted
      }
      verifiableUsers {
        teamWithMembers {
          team {
            id
            name
          }
          members {
            ...TeamMember
          }
        }
        user {
          ...TeamMemberUser
        }
      }
      onlineReview {
        ...OnlineReviewInfo
      }
    }
  }
}