query getLinkToPrivateStudentGitlabProjectByAnswerId($studentAnswerId: ID!) {
  student {
    getLinkToPrivateStudentGitlabProjectByAnswerId(answerId: $studentAnswerId) {
      httpsLink
      sshLink
    }
  }
}