query getLinkToPrivateStudentGitlabProjectByAnswerId($answerId: ID!) {
  student {
    getPrivateGitlabProjectLinkInfoByAnswerId(answerId: $answerId) {
      httpsLink
      sshLink
      status
    }
  }
}