query getNotificationUserSettings {
  notificationConfiguration {
    settings: getNotificationUserSettings {
      groupTypeId
      groupTypeName
      typeId
      typeName
      channelId
      channelName
      channelActive
      channelActiveSystem
      channelLockedSystem
      isMutable
    }
  }
}