query getStageInfo {
  user {
    getCurrentUser {
      id
      studentRoles {
        status
        school {
          organizationType
        }
        stageGroup {
          classSubjects {
            stage {
              name
            }
          }
          name
          stage
          isActive
        }
      }
    }
    getAllStagesTenantAware {
      id
      name
    }
  }
}