query getTasksById($goalId: ID!, $localCourseId: ID, $taskId: ID!, $language: String) {
  school21 {
    getTasksById(
      goalId: $goalId
      localCourseId: $localCourseId
      taskId: $taskId
      language: $language
    ) {
      id
      task {
        id
        content {
          id
          body
        }
        translatedData
      }
    }
  }
}