mutation leaveTeam($teamId: UUID!, $exitReasonId: Int, $exitReasonDescription: String) {
  student {
    exitStudentFromTeam(
      teamId: $teamId
      exitReasonId: $exitReasonId
      exitReasonDescription: $exitReasonDescription
    )
  }
}