fragment StudyProcessFile on StudyProcessFile {
  studyProcessFileId
  link
  status
  statusDetails
  updateDateTime
  creatorLogin
  fileExtension
  fileSize
}

mutation markFileSolutionPending($taskId: ID!, $initialFileEvents: [StudyProcessFileInitialInput!]!) {
  sc21StudentTaskCheck {
    markFileSolutionPending(taskId: $taskId, initialFileEvents: $initialFileEvents) {
      ...StudyProcessFile
    }
  }
}