mutation markTournamentNotificationShown($userTournamentResultId: [UUID!]!) {
  student {
    markTournamentResultAsShown(userTournamentResultIds: $userTournamentResultId) {
      id
      isShown
    }
  }
}