fragment StudyProcessFile on StudyProcessFile {
  studyProcessFileId
  link
  status
  updateDateTime
  creatorLogin
  fileExtension
  fileSize
}

mutation markFileSolutionUploadedStatus($taskId: ID!, $studyProcessFileIds: ID!) {
  sc21StudentTaskCheck {
    markFileSolutionUploadedStatus(
      taskId: $taskId
      studyProcessFileIds: $studyProcessFileIds
    ) {
      ...StudyProcessFile
    }
  }
}