fragment OnlineReviewVideoInfo on OnlineReviewVideo {
  onlineVideoId
  link
  status
  updateDateTime
  fileSize
}

mutation markOnlineReviewVideoUploaded($filledChecklistId: ID!, $onlineReviewId: ID!) {
  school21 {
    markP2pCheckVideoUploaded(
      filledChecklistId: $filledChecklistId
      onlineReviewId: $onlineReviewId
    ) {
      ...OnlineReviewVideoInfo
    }
  }
}