query publicProfileGetProjectsStatuses($studentId: UUID!, $projects: [StudentItemEntityInput!]!) {
  school21 {
    getStudentProjectStatusesForPublicProfileV2(
      studentId: $studentId
      projects: $projects
    ) {
      groupName
      name
      experience
      finalPercentage
      goalId
      goalStatus
      amountAnswers
      amountReviewedAnswers
      executionType
      localCourseId
      courseType
      displayedCourseStatus
    }
  }
}