mutation saveStudentFeedbackResults($studentFeedbackId: ID!, $studentFeedbackResults: [StudentFeedbackResultInput!]!) {
  sc21StudentTaskCheck {
    saveStudentFeedbackResults(
      studentFeedbackId: $studentFeedbackId
      studentFeedbackResults: $studentFeedbackResults
    )
  }
}