mutation saveHonorRatings($studentHonorRatings: [StudentHonorRatingInput!]!) {
  honorRating {
    saveStudentHonorRatings(studentHonorRatings: $studentHonorRatings) {
      studentHonorRatingId
    }
  }
}