query widgetAchievementsGetLastBadges($limit: Int) {
  student {
    getLastBadges(limit: $limit) {
      id
      points
      badge {
        name
        avatarUrl
      }
      award {
        awardBounties {
          awardLevelId
        }
      }
    }
  }
}